title: "Dr. Mehrdad Zakershahrak - Lead AI/ML Scientist"
author: "Dr. Mehrdad Zakershahrak"
description: "Expert in Reinforcement Learning, Human-Centered AI, and High-Performance Computing. Pioneering AI integration in data architectures and robotics."
keywords: "AI, Machine Learning, Reinforcement Learning, Human-Centered AI, Robotics"
permalink: /:categories/:year/:month/:day/:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# SEO settings
twitter:
  username: mehrdadhw
  card: summary_large_image
social:
  name: Dr. Mehrdad Zakershahrak
  links:
    - https://www.linkedin.com/in/mehrdadzaker/
    - https://github.com/mehrdadzakershahrak
    - https://scholar.google.com/citations?user=Y_-UFnUAAAAJ&hl=en

# Layout
show_excerpts: true
show_sidebar: true

# Menu
navigation:
  - {file: "index.html", title: "Home"}
  - {file: "about.markdown", title: "About Me"}
  - {file: "blog.html", title: "Blog"}

external:
  - {title: Github, icon: github, url: "https://github.com/mehrdadzakershahrak"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/mehrdadzaker/"}
  - {title: Google Scholar, icon: graduation-cap, url: "https://scholar.google.com/citations?user=Y_-UFnUAAAAJ&hl=en"}

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

paginate: 5
paginate_path: "/blog/page:num/"

collections:
  blog:
    output: true
    permalink: /blog/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"