title: "Dr. Mehrdad Zakershahrak - AI/ML Scientist and Researcher"
author: "Dr. Mehrdad Zakershahrak"
description: "Explore the work of Dr. Mehrdad Zakershahrak, a Lead AI/ML Scientist specializing in Reinforcement Learning, Human-Centered AI, and High-Performance Computing."
keywords: "AI, Machine Learning, Reinforcement Learning, Human-Centered AI, Robotics, Data Science"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# SEO settings
twitter:
  username: your_twitter_handle
  card: summary_large_image
logo: /path/to/your/logo.png
social:
  name: Dr. Mehrdad Zakershahrak
  links:
    - https://www.linkedin.com/in/mehrdadzaker/
    - https://github.com/mehrdadzakershahrak
    - https://scholar.google.com/citations?user=Y_-UFnUAAAAJ&hl=en

# Layout
show_excerpts: true
show_frame: true
show_sidebar: true
minimal: false

# Menu
navigation:
  - {file: "index.html", title: "Home"}
  - {file: "about.markdown", title: "About Me"}
  - {file: "blog.md", title: "Blog"}
  - {file: "projects.md", title: "Projects"}
  - {file: "contact.md", title: "Contact"}

external:
  - {title: Github, icon: github, url: "https://github.com/mehrdadzakershahrak"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/mehrdadzaker/"}
  - {title: Google Scholar, icon: graduation-cap, url: "https://scholar.google.com/citations?user=Y_-UFnUAAAAJ&hl=en"}

# Plugins and other settings (as previously configured)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives

paginate: 5
paginate_path: "/blog/page:num/"

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/