title: "Mehrdad - Lead AI/ML Scientist"
author: "Mehrdad"
description: "Expert in Reinforcement Learning, Human-Centered AI, and High-Performance Computing. Pioneering AI integration in data architectures and robotics."
baseurl: ""
url: "https://mehrdadzakershahrak.github.io"
permalink: /:year/:month/:day/:title/
paginate: 5

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Social links
github_username: mehrdadzakershahrak
linkedin_username: mehrdadzaker
google_scholar: Y_-UFnUAAAAJ

# Pagination
paginate_path: "/blog/page:num/"

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"