title: Mehrdad Zakershahrak
description: Personal website
baseurl: ""
url: "https://www.mehrdadzaker.com"
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  math_engine_opts:
    preview: true