title: "Mehrdad - Lead AI/ML Scientist"
author: "Mehrdad"
description: "Expert in Reinforcement Learning, Human-Centered AI, and High-Performance Computing. Pioneering AI integration in data architectures and robotics."
baseurl: ""
url: "https://mehrdadzakershahrak.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Custom settings
header_pages:
  - about.md
  - blog.md

# Social links
github_username: mehrdadzakershahrak
linkedin_username: mehrdadzaker
google_scholar: Y_-UFnUAAAAJ

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Collections
collections:
  blog:
    output: true
    permalink: /blog/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"